./" color_game
.TH color_game 3 "2021" "file_view"

.SH NAME
	color_game
.SH DESCRIPTION
	color_game is a game where you match colors.
.SH RULES
	You win by filling the whole map with one color.

	-Red eats yellow.

	-Yellow eats blue.

	-Green eats red.

	-blue eats green.

	-Black becomes the eater of what touches it.

	-White becomes the opposite of what touches it.

	-All browns become the first color to go extinct.
.SH MAPS
	You can add maps by adding a .json file to your map folder in /usr/local/share/color_game/

	Use the example.txt file to learn how to make a map.
